name: emacs-24bit-colour
version: 24.4
summary: GNU Emacs 24.4 + 24-bit colour support
description: Emacs, the extensible, customizable, self-documenting real-time display editor.
confinement: strict
grade: stable

apps:
  emacs:
    command: emacs
    plugs: [home, x11, unity7, gsettings, pulseaudio, network, network-bind]
  emacsclient:
    command: emacsclient
    plugs: [home, x11, unity7, gsettings, pulseaudio, network, network-bind]
  ctags:
    command: ctags
  ebrowse:
    command: ebrowse
  etags:
    command: etags
  grep-changelog:
    command: grep-changelog

parts:
  emacs:
    plugin: autotools
    configflags:
      - --without-jpeg
      - --without-sound
    source: https://github.com/frobware/emacs/archive/emacs-24.4-24bit-colour.tar.gz
    source-type: tar
    install-via: prefix
    build-packages:
      - autoconf
      - automake
      - autotools-dev
      - imagemagick
      - sharutils
      - texinfo
      - libgnutls-dev
      - libgif-dev
      - libxpm-dev
      - libjpeg-dev
      - libtiff5-dev
      - libncursesw5-dev
      - libsm-dev
      - libxft-dev
    stage-packages:
      - libgnutls30
      - libgif7
      - libxpm4
      - libjpeg8
      - libtiff5
      - libncursesw5
      - libsm6
      - libxft2
    after:
      - desktop-gtk3
